plugins:
  discourse_support_reminder_enabled:
    default: true
    client: true
  discourse_support_reminder_categories_names:
    client: false
    type: category_list
    default: 'none'
  discourse_support_reminder_message:
    client: false
    type: string
    default: 'Hello, this is a friendly reminder because this is your first time creating a topic (or it has been a while since your last topic) in this category.<br><br>Please note that most of the support is provided by the FiveM community on a voluntary basis. We ask you to be patient; there is no guarantee we have a solution to your problem(s). To avoid unnecessary/duplicate topics, please browse the forums before creating a topic.<br><br>To improve your chances of your issue(s) being solved, please provide as much information as possible about the issue(s) you are having. Also —whenever possible— please use the template given to you when creating a topic.<br><br>Thanks for keeping these forums tidy!<br>:mascot:'
  discourse_support_reminder_excempt_staff:
    client: true
    type: bool
    default: true